### PR TITLE
conflict resolve - Merge release-3.1.0 into release-3.2.0

### PR DESCRIPTION
**Pull request by manjudr**
…se-3.2.0

### CODE REVIEW

**Review by Hari-stackroute — COMMENTED** [review]
Looks ok. My changes are not affected.

**Comment by manjudr** [comment]
@kumarks1122 @Hari-stackroute  @ishawakankar Please check is your changes are fine not.

**Comment by kumarks1122** [comment]
My changes are not affected.

**Comment by manjudr** [comment]
ref - https://github.com/Sunbird-Ed/sunbird-data-products/pull/208

**Pull request closed without merging**
