### PR TITLE
Issue #SB-30518 | Session id added

### PR DESCRIPTION
**Pull request by surabhi-mahawar**
<table>
<td>
  <a href="https://project-sunbird.atlassian.net/browse/SB-30518" title="SB-30518" target="_blank">TaskSB-30518</a>  Addition of Session Id
  </td></table>
  <br />
 

<table>
<td>
  <a href="https://project-sunbird.atlassian.net/browse/SB-30518" title="SB-30518" target="_blank">TaskSB-30518</a>  Addition of Session Id
  </td></table>
  <br />

Added session id in UCI Response exhaust

### CODE REVIEW

**Comment by surabhi-mahawar** [comment]
@manjudr 
Can you please merge this PR I need to deploy this as a part of hotlfix on pre-prod & prod, as 5.0.0 is not yet approved for deployment.

**Comment by surabhi-mahawar** [comment]
@manjudr / @sowmya-dixit 
Can you please merge this PR I need to deploy this as a part of hotlfix on pre-prod & prod, as 5.0.0 is not yet approved for deployment.

**Comment by sowmya-dixit** [comment]
@surabhi-mahawar Latest release branch for this repo is `release-4.10.5`, please raise PR to this branch.

**Review by anandp-syngenta — APPROVED** [review]
Approved :+1:

**Comment by anandp504** [comment]
Incorrect release branch. Closing the PR.

**Pull request closed without merging**
